### ISSUE TITLE
Plugin throws exception "Unsupported major.minor version 51.0"

### ISSUE THREAD

**Issue by Vinai** [dkvashninbay/magento2plugin#11]
I just tried to install and use the plugin as described at the [Installation section of the Readme](https://github.com/dkvashninbay/magento2plugin/blob/master/README.md#installation).

After restarting PHPStorm the exceptions
```
09:36:28 PluginException: com/magento/idea/magento2plugin/SettingsForm : Unsupported major.minor version 51.0 [Plugin: com.magento.idea.magento2plugin]
09:37:52 PluginException: com/magento/idea/magento2plugin/php/linemarker/PluginLineMarkerProvider : Unsupported major.minor version 51.0 [Plugin: com.magento.idea.magento2plugin]
09:38:08 PluginException: com/magento/idea/magento2plugin/php/inspections/MagentoApiInspection : Unsupported major.minor version 51.0 [Plugin: com.magento.idea.magento2plugin]
```
is logged in the PHPStorm event log.

There is no "Magento2" in the dialogue window "Settings / Preferences / Other Settings"

Here is the About window of my PHPStorm:

<img width="394" alt="bildschirmfoto 2016-03-14 um 09 40 57" src="https://cloud.githubusercontent.com/assets/72463/13739015/e71abd88-e9c8-11e5-8b60-cfcb07a5691e.png">

The project contains a composer based Magento 2 installation. It is installed in a sub directory of the project base dir:

```
$ tree -L 2 .
.
└── mage2-ce
    ├── CHANGELOG.md
    ├── CONTRIBUTING.md
    ├── CONTRIBUTOR_LICENSE_AGREEMENT.html
    ├── COPYING.txt
    ├── Gruntfile.js
    ├── LICENSE.txt
    ├── LICENSE_AFL.txt
    ├── app
    ├── bin
    ├── composer.json
    ├── composer.lock
    ├── dev
    ├── index.php
    ├── lib
    ├── nginx.conf.sample
    ├── package.json
    ├── php.ini.sample
    ├── phpserver
    ├── pub
    ├── setup
    ├── update
    ├── var
    └── vendor

11 directories, 13 files
```
I also tried creating a project with Magento 2 as the project base dir, but that made no difference. The same exceptions are logged.  

Java Version:
```
$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```
Seems like PHPStorm is running on a different version 1.6 of Java though based on its about dialogue.

Here are is the stack trace of the first exception

```
com/magento/idea/magento2plugin/php/linemarker/PluginLineMarkerProvider : Unsupported major.minor version 51.0 [Plugin: com.magento.idea.magento2plugin]
com.intellij.diagnostic.PluginException: com/magento/idea/magento2plugin/php/linemarker/PluginLineMarkerProvider : Unsupported major.minor version 51.0 [Plugin: com.magento.idea.magento2plugin]
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
	at com.intellij.openapi.extensions.CustomLoadingExtensionPointBean.instantiateExtension(CustomLoadingExtensionPointBean.java:47)
	at com.intellij.lang.LanguageExtensionPoint.access$000(LanguageExtensionPoint.java:28)
	at com.intellij.lang.LanguageExtensionPoint$1.compute(LanguageExtensionPoint.java:42)
	at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
	at com.intellij.lang.LanguageExtensionPoint.getInstance(LanguageExtensionPoint.java:53)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:154)
	at com.intellij.openapi.util.KeyedExtensionCollector.buildExtensions(KeyedExtensionCollector.java:127)
	at com.intellij.openapi.util.KeyedExtensionCollector.forKey(KeyedExtensionCollector.java:115)
	at com.intellij.lang.LanguageExtension.allForLanguage(LanguageExtension.java:75)
	at com.intellij.lang.LanguageExtension.allForLanguageOrAny(LanguageExtension.java:87)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.getMarkerProviders(LineMarkersPass.java:154)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:111)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
Caused by: java.lang.UnsupportedClassVersionError: com/magento/idea/magento2plugin/php/linemarker/PluginLineMarkerProvider : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:124)
	... 34 more



com.intellij.diagnostic.PluginException: com/magento/idea/magento2plugin/php/inspections/MagentoApiInspection : Unsupported major.minor version 51.0 [Plugin: com.magento.idea.magento2plugin]
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:130)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:63)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:156)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:84)
	at com.intellij.codeInspection.ex.InspectionProfileWrapper.checkInspectionsDuplicates(InspectionProfileWrapper.java:68)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.getInspectionTools(LocalInspectionsPass.java:651)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPassFactory$MyLocalInspectionsPass.getInspectionTools(LocalInspectionsPassFactory.java:95)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:141)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
Caused by: java.lang.UnsupportedClassVersionError: com/magento/idea/magento2plugin/php/inspections/MagentoApiInspection : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:260)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:256)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:225)
	at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:124)
	... 29 more
```

What am I doing wrong? Is there any other information I can provide to help pinpoint what is going on?

**Comment by Vinai** [comment]
I've managed to fix the error by using the action "Switch IDE book JDK" to configure the local 1.8 JRE for PHPStorm. I don't know why the bundled version was 1.6. Other installations came with a bundled 1.8. Anyway, all working now.
