### ISSUE TITLE
Issue in PhpStorm 2017.1.4

### ISSUE THREAD

**Issue by akuzhel** [dkvashninbay/magento2plugin#17]
Got IDE Fatal error.

Error message: 
_com.jetbrains.php.lang.psi.PhpFileImpl cannot be cast to com.intellij.psi.xml.XmlFile_

Details: 
```
com.jetbrains.php.lang.psi.PhpFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
java.lang.ClassCastException: com.jetbrains.php.lang.psi.PhpFileImpl cannot be cast to com.intellij.psi.xml.XmlFile
	at com.magento.idea.magento2plugin.xml.di.index.TypeConfigurationFileBasedIndex.getClassConfigurations(TypeConfigurationFileBasedIndex.java:59)
	at com.magento.idea.magento2plugin.php.linemarker.DiConfigurationCollector.collect(ClassConfigurationLineMarkerProvider.java:78)
	at com.magento.idea.magento2plugin.php.linemarker.DiConfigurationCollector.collect(ClassConfigurationLineMarkerProvider.java:74)
	at com.magento.idea.magento2plugin.php.linemarker.ClassConfigurationLineMarkerProvider.collectSlowLineMarkers(ClassConfigurationLineMarkerProvider.java:44)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:209)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.a(LineMarkersPass.java:116)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:96)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:106)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1153)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:242)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by wildcard27** [comment]
Getting this too

**Comment by theycallmepepper** [comment]
I don't recall seeing any errors with 2017.2 and I just opened things up on 2017.3.EAP.  Are you able to update and reproduce?
