### ISSUE TITLE
Already disposed: Project (Disposed) error message in phpstorm 10.0.3

### ISSUE THREAD

**Issue by nagno** [dkvashninbay/magento2plugin#9]
Hi,

The IDE was sitting in the background, when the error happened.

The exception details:
```
Already disposed: Project (Disposed) hemseedtest
java.lang.AssertionError: Already disposed: Project (Disposed) hemseedtest
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:170)
	at com.intellij.psi.PsiManager.getInstance(PsiManager.java:39)
	at com.magento.idea.magento2plugin.php.module.MagentoComponentManager.loadModules(MagentoComponentManager.java:103)
	at com.magento.idea.magento2plugin.php.module.MagentoComponentManager.getComponents(MagentoComponentManager.java:67)
	at com.magento.idea.magento2plugin.php.module.MagentoComponentManager.getAllComponents(MagentoComponentManager.java:44)
	at com.magento.idea.magento2plugin.php.module.MagentoComponentManager.getComponentOfTypeForFile(MagentoComponentManager.java:88)
	at com.magento.idea.magento2plugin.xml.index.LineMarkerXmlTagDecorator.getComponentName(LineMarkerXmlTagDecorator.java:66)
	at com.magento.idea.magento2plugin.xml.index.LineMarkerXmlTagDecorator.getName(LineMarkerXmlTagDecorator.java:85)
	at com.magento.idea.magento2plugin.php.linemarker.ClassConfigurationLineMarkerProvider.collectSlowLineMarkers(ClassConfigurationLineMarkerProvider.java:61)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
	at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1177)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by dkvashninbay** [comment]
Hi!
Took in progress.
But this issue seems strange, as i thought i've already fixed that in https://github.com/dkvashninbay/magento2plugin/commit/853d2170d2c89601534266b05e2ea9fd7518157f  + none from my team gets such exception.
Maybe you can tell a bit more details like operating system and phpstorm version used?
Thanks!

**Comment by nagno** [comment]
Hi,

PhpStorm: 10.0.3 (143.1770).
My OS is: Mac OSX 10.11.3 (15D21)
JRE: 1.8.0_40-release-b119 x86_64
Module: v0.2.1

Please let me know, if I can help anything further.

Regards,
Norbert

**Comment by dkvashninbay** [comment]
Fixed in https://github.com/dkvashninbay/magento2plugin/commit/8858bab5bee4efd3690c06cd50435b11292b4bb4
will be available next week!

**Comment by nagno** [comment]
Thanks!
